#!/bin/bash
#
# udev-post     Post script for udev, after all filesystems are mounted
#
# Authors:      Harald Hoyer <harald@redhat.com>
#
# chkconfig: 12345 26 75
# description: Moves the generated persistent udev rules to /etc/udev/rules.d
# 
### BEGIN INIT INFO
# Default-Start: 12345
# Default-Stop:  0 6
# Required-Start: $local_fs
# Required-Stop: 
# Short-Description: Moves the generated persistent udev rules to /etc/udev/rules.d
# Description: Moves the generated persistent udev rules to /etc/udev/rules.d
# Provides: udev-post
### END INIT INFO

. /etc/rc.d/init.d/functions

# See how we were called.
case "$1" in
  start|reload)
	[ -w /var/lock/subsys ] || exit 4
	STRING=$"Retrigger failed udev events"
	echo -n $STRING 
    # This has been deprecated by upstream, we need to remove this.
    # No replacement has been provided, upstream just thinks it's wrong.
	/sbin/udevadm trigger --type=failed --action=add
	success "$STRING"
	echo

	STRING=$"Adding udev persistent rules"
	
	# copy the rules generated before / was mounted read-write
	for file in /dev/.udev/tmp-rules--*; do
		dest=${file##*tmp-rules--}
		# check, if anything is todo
		[ "$dest" = '*' ] && exit 0
		echo -n $STRING 
		cat $file >> /etc/udev/rules.d/$dest
		rc=$?
		rm -f $file
		if [ "$rc" -eq "0" ]; then
			success "$STRING"
			echo
		elif [ "$rc" -eq "1" ]; then
			failure "$STRING"
			echo
            	fi
	done

	touch /var/lock/subsys/udev-post
	exit 0
	;;
  stop)
	[ -w /var/lock/subsys ] || exit 4
	rm -f /var/lock/subsys/udev-post
	exit 0
	;;
  status)
	exit 3
	;;
  *)
        echo $"Usage: $0 {start|stop|reload}"
        exit 2
esac
exit 0
